colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
enableBreadcrumbs = true
defaultBackgroundImage = "/images/hero-bg.jpg"
defaultFeaturedImage = "/images/hero-bg.jpg"
fingerprintAlgorithm = "sha512"

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  layoutBackgroundBlur = true

[article]
  showViews = true
  showLikes = true
  showDate = true
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = false
  showTaxonomies = true
  showWordCount = false
  sharingLinks = ["twitter", "linkedin", "telegram", "email"]

[list]
  showHero = false
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showTaxonomies = true

# Firebase (阅读统计)
[firebase]
  apiKey = "AIzaSyACZ1DF9g76lMhiSEKkGs2BVQfA-QlA740"
  authDomain = "byslab-log.firebaseapp.com"
  projectId = "byslab-log"
  storageBucket = "byslab-log.firebasestorage.app"
  messagingSenderId = "127774753709"
  appId = "1:127774753709:web:3293ecb7d4c5f1d4dd9724"
  measurementId = "G-YTE1P6B13G"
